#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : qsstv
Version  : 9.4.4
Release  : 4
URL      : http://users.telenet.be/on4qz/qsstv/downloads/qsstv_9.4.4.tar.gz
Source0  : http://users.telenet.be/on4qz/qsstv/downloads/qsstv_9.4.4.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : GPL-3.0
Requires: qsstv-bin = %{version}-%{release}
Requires: qsstv-data = %{version}-%{release}
Requires: qsstv-license = %{version}-%{release}
BuildRequires : alsa-lib-dev
BuildRequires : buildreq-qmake
BuildRequires : fftw-dev
BuildRequires : mesa-dev
BuildRequires : pkgconfig(Qt5Concurrent)
BuildRequires : pkgconfig(Qt5Core)
BuildRequires : pkgconfig(Qt5Gui)
BuildRequires : pkgconfig(Qt5Network)
BuildRequires : pkgconfig(Qt5Widgets)
BuildRequires : pkgconfig(Qt5Xml)
BuildRequires : pkgconfig(hamlib)
BuildRequires : pkgconfig(libopenjp2)
BuildRequires : pkgconfig(libpulse)
BuildRequires : pkgconfig(libv4l2)
BuildRequires : pkgconfig(libv4lconvert)
Patch1: 0001-Set-prefix-to-usr.patch

%description
For the full manual please go to
http://users.telenet.be/on4qz/qsstv/manual/index.html

%package bin
Summary: bin components for the qsstv package.
Group: Binaries
Requires: qsstv-data = %{version}-%{release}
Requires: qsstv-license = %{version}-%{release}

%description bin
bin components for the qsstv package.


%package data
Summary: data components for the qsstv package.
Group: Data

%description data
data components for the qsstv package.


%package license
Summary: license components for the qsstv package.
Group: Default

%description license
license components for the qsstv package.


%prep
%setup -q -n qsstv_9.4.4
cd %{_builddir}/qsstv_9.4.4
%patch1 -p1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export GCC_IGNORE_WERROR=1
%qmake -config ltcg -config fat-static-lto
test -r config.log && cat config.log
make  %{?_smp_mflags}

%install
export SOURCE_DATE_EPOCH=1612217095
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/qsstv
cp %{_builddir}/qsstv_9.4.4/COPYING %{buildroot}/usr/share/package-licenses/qsstv/a594e9581fbfae392fc70fc1974aa6e1169bbbe8
%make_install

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/qsstv

%files data
%defattr(-,root,root,-)
/usr/share/applications/qsstv.desktop

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/qsstv/a594e9581fbfae392fc70fc1974aa6e1169bbbe8
