#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : qsstv
Version  : 9.5.8
Release  : 10
URL      : https://www.qsl.net/o/on4qz/qsstv/downloads/qsstv_9.5.8.tar.gz
Source0  : https://www.qsl.net/o/on4qz/qsstv/downloads/qsstv_9.5.8.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : GPL-3.0
Requires: qsstv-bin = %{version}-%{release}
Requires: qsstv-data = %{version}-%{release}
Requires: qsstv-license = %{version}-%{release}
BuildRequires : alsa-lib-dev
BuildRequires : buildreq-qmake
BuildRequires : doxygen
BuildRequires : fftw-dev
BuildRequires : graphviz
BuildRequires : mesa-dev
BuildRequires : pkgconfig(Qt5Core)
BuildRequires : pkgconfig(Qt5Gui)
BuildRequires : pkgconfig(Qt5Network)
BuildRequires : pkgconfig(Qt5Widgets)
BuildRequires : pkgconfig(Qt5Xml)
BuildRequires : pkgconfig(hamlib)
BuildRequires : pkgconfig(libopenjp2)
BuildRequires : pkgconfig(libpulse)
BuildRequires : pkgconfig(libv4l2)
BuildRequires : pkgconfig(libv4lconvert)
BuildRequires : qwt-dev
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}
Patch1: 0001-Replace-dep-libqwt-qt5-with-libqwt.patch
Patch2: 0002-Filter-out-fewer-sound-devices.patch

%description
For the full manual please go to
http://users.telenet.be/on4qz/qsstv/manual/index.html

%package bin
Summary: bin components for the qsstv package.
Group: Binaries
Requires: qsstv-data = %{version}-%{release}
Requires: qsstv-license = %{version}-%{release}

%description bin
bin components for the qsstv package.


%package data
Summary: data components for the qsstv package.
Group: Data

%description data
data components for the qsstv package.


%package license
Summary: license components for the qsstv package.
Group: Default

%description license
license components for the qsstv package.


%prep
%setup -q -n qsstv
cd %{_builddir}/qsstv
%patch1 -p1
%patch2 -p1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export GCC_IGNORE_WERROR=1
export CFLAGS="$CFLAGS -fdebug-types-section -femit-struct-debug-baseonly -g1 -gno-column-info -gno-variable-location-views -gz "
export FCFLAGS="$FFLAGS -fdebug-types-section -femit-struct-debug-baseonly -g1 -gno-column-info -gno-variable-location-views -gz "
export FFLAGS="$FFLAGS -fdebug-types-section -femit-struct-debug-baseonly -g1 -gno-column-info -gno-variable-location-views -gz "
export CXXFLAGS="$CXXFLAGS -fdebug-types-section -femit-struct-debug-baseonly -g1 -gno-column-info -gno-variable-location-views -gz "
%qmake -config ltcg -config fat-static-lto  PREFIX=/usr \
INSTALLS+="dox data shortcutfiles" \
CONFIG+="debug"
test -r config.log && cat config.log
make  %{?_smp_mflags}

%install
export SOURCE_DATE_EPOCH=1673393547
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/qsstv
cp %{_builddir}/qsstv/COPYING %{buildroot}/usr/share/package-licenses/qsstv/a594e9581fbfae392fc70fc1974aa6e1169bbbe8 || :
%make_install

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/qsstv

%files data
%defattr(-,root,root,-)
/usr/share/applications/qsstv.desktop
/usr/share/icons/hicolor/42x42/apps/qsstv.png

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/qsstv/a594e9581fbfae392fc70fc1974aa6e1169bbbe8
